add first part of project
KingSLi/mipt-cis-react pull request #3
Opened 2021-11-03 11:41 UTC by KingSLi

2021-11-05 17:34 UTC, KingSLi commented
Добавил вторую часть дз. Вместо главной страницы, добавил станицу Запись, на которой форма для записи

2021-11-06 19:00 UTC, dshuran requested changes
Если я выберу текущую дату и нажму ОК, то выберется текущее время, а так быть не должно: нужно ближайшее кратное 30

2021-11-07 10:58 UTC, dshuran approved these changes

2021-11-07 10:58 UTC, dshuran commented on washing_timetable/src/App.js
> +          <Menu theme="dark" mode="horizontal" defaultSelectedKeys={selectedKeys}>
Лучше использовать тут проп selectedKeys, а в defaultSelectedKeys некоорое стандартное значение задать. Можно пофиксить в рамках следующего PR

2021-11-07 10:59 UTC, merged